name: Java CD (Deployment)

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Local Dependencies
      working-directory: ./TourGuide
      run: |
        mvn install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

    - name: Package JAR
      working-directory: ./TourGuide
      run: mvn package -DskipTests

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tourguide-app
        path: TourGuide/target/*.jar